version: '2'
services:
  mysql:
    image: mysql
    container_name: makgora_mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: makgora
      MYSQL_USER: makgora
      MYSQL_PASSWORD: m4kgor4
      MYSQL_ROOT_PASSWORD: rootmakgora
  rails:
    build: .
    image: rails:1.0
    container_name: makgora_rails
    expose:
      - "3000"
    links:
      - mysql
    volumes:
      - .:/var/www/makgoradota2
  nginx:
    build: 
      context: .
      dockerfile: config/containers/Dockerfile
    image: nginx-rails:1.0
    container_name: makgora_nginx
    volumes_from:
      - rails
    links:
      - rails
    ports:
      - "80:80"